Upgrade Helm chart
spotahome/redis-operator pull request #323
Opened 2021-09-20 11:32 UTC by obsessionsys

Fixes # .

Changes proposed on the PR:
- Updating the helm chart according to best-practice and templates
- More flexible configuration of deployment variables using the helm chart
- Adding the use of a docker private registry

2021-09-22 16:00 UTC, ese requested changes
Looks great, thanks for the PR

2021-09-22 16:00 UTC, ese commented on charts/redisoperator/Chart.yaml
> +appVersion: 3.1.0
redis-operator is currently version 1.0.0
```suggestion
appVersion: 1.0.0
```

2021-09-22 16:00 UTC, ese commented on charts/redisoperator/Chart.yaml
> +version: 3.1.2
I would update the version of the chart to 4.0.0 since it includes breaking changes like modifications on immutable fields like deployment selector

2021-09-22 16:00 UTC, ese commented on charts/redisoperator/Chart.yaml
> +version: 3.1.2
```suggestion
version: 4.0.0
```

2021-11-22 09:05 UTC, obsessionsys commented
@ese 
Hi Sergio, 
At the moment an error occurred when running the script./scripts/check.sh
Judging by the contents of the script, the golang linter is launched which doesn’t pass within the linter code.
Also there is a conflict in the charts/redisoperator/templates/rbac file.yaml in this pull request, which I can’t resolve according to my repository access rights.
Please let me know if I can help to resolve this conflict? Does ./scripts/check.sh checking affect to this merge pull request?

2022-01-11 11:53 UTC, ese approved these changes

2022-01-11 12:11 UTC, merged